language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

cache:
  - pip

install:
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO_VERSION

script:
  - python manage.py test
